name: 'Meson Builder'

description:
  'builds meson projects and runs tests, optionally using sanitizers'

inputs:
  image_name:
    description:
      'image from this repository to use'
    required: true
  sanitizer:
    description:
      'sanitizer to use, like none, address, thread...'
    default: 'none'
    required: false
  options:
    description:
      'further options to pass to meson'
    default: '-Dcpp_debugstl=true'
    required: false
  build_dir:
    description: 'meson build dir, persists after run'
    default: 'build'
    required: false
  username:
    description: 'username for docker registry'
    required: false
  password:
    description: 'password for docker registry'
    required: false
  registry:
    description: 'docker registry'
    required: false
    
runs:
  using: 'node12'
  main: 'action.js'
