name: Deploy Docker Images

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 1 * *'
      
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    name: deploy ${{ matrix.image }}
    strategy:
      matrix:
        image: [arch-gcc, arch-clang, debian-gcc, debian-clang, site-builder]
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: docker/build-push-action@v1.1.0
        name: build/deploy ${{ matrix.image }}
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: robinmarchart/meson-builder/${{ matrix.image }}
          path: ${{ matrix.image }}
